config/routes.rb
Rails.application.routes.draw do
  
  resources :pos, only: :index do
    member do
      post :cart
    end
  end

  namespace :api do
    resources :locate, only: :[] do
      member do
        get :beacon
        get :barcode
      end
    end
    
    resources :pos, only: :[] do
      member do
        post :cart
      end
    end
  end

  resources :downloads, only: :[] do
    collection do
      get :android
      get :qr_code
    end
  end
  
  namespace :admin do
    resources :api_requests, only: :index
    
    root to: "api_requests#index"
  end

  root to: 'pos#index'
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "Find Your Free Learning Here !", name: "description"}
    %meta{content: "iLearn Admin", name: "author"}
    %title Admin

    = favicon_link_tag
    = stylesheet_link_tag  'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    #adminTopnav.topnav
      %b= link_to 'Admin', '#', class: admin_active_class('home')
      = link_to 'Open PoS', root_path, style: "border-left: 1px solid #ccc; border-right: 1px solid #ccc;", target: :_blank
      = link_to 'API Requests', admin_api_requests_path, class: admin_active_class('api_requests')
      %a.icon{href: "javascript:void(0);", onclick: "toggleAdminTopnav();", style: "font-weight: bold;"} &#9776;
    .admin-container
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title MSCO
    = favicon_link_tag
    = csrf_meta_tags
    =# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    =# javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{"data-turbolinks-track" => "reload", href:  "//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.css", media:  "all", rel:  "stylesheet"}
    %link{"data-turbolinks-track" => "reload", href:  "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css", media:  "all", rel:  "stylesheet"}
    %link{"data-turbolinks-track" => "reload", href:  "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css", media:  "all", rel:  "stylesheet"}

    %script{"data-turbolinks-track" => "reload", src:  "//cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.0/turbolinks.min.js"}
    %script{"data-turbolinks-track" => "reload", src:  "//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
    %script{"data-turbolinks-track" => "reload", src:  "//cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.1/rails.min.js"}
    %script{"data-turbolinks-track" => "reload", src:  "//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.js"}
    %script{"data-turbolinks-track" => "reload", src:  "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"}

  %body
    %nav.navbar.navbar-expand-sm.navbar-light.bg-faded{style: "background-color: #e3f2fd;"}
      %button.navbar-toggler{"aria-controls" => "nav-content", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#nav-content", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      / Brand
      = link_to "POS", root_path, class: "navbar-brand"
      = link_to (fa_icon "download", text: "Android"), qr_code_downloads_path(file: "#{apk_download_filename}"), class: 'navbar-brand pull-right'

    = yield